platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :generate_multiple_pod_projects => true

target 'WalletConnect_Example' do
  pod 'WalletConnect', :path => '../'
  pod 'TrustWalletCore' 
  pod 'SwiftLint' 
  target 'WalletConnect_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
		end
	end
end
